version: '3.8'

services:
  react-app:
    image: react-app-test
    container_name: react-app-test
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - '.:/app'
      - '/app/node_modules'

    ports:
      - '3001:3000'

    environment:
      - CHOKIDAR_USEPOLLING=true